# Generated by Django 2.1.12 on 2019-10-10 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgroup',
            name='main_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_groups', to='auth.Group'),
        ),
    ]
