# Generated by Django 2.1.12 on 2019-10-23 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_auto_20191010_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgroup',
            name='main_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_groups', to='auth.Group'),
        ),
    ]
