# Generated by Django 2.1.12 on 2019-10-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamsettings1',
            old_name='salesorderclassification',
            new_name='conditions',
        ),
    ]
