# Generated by Django 2.1.12 on 2019-10-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_auto_20191024_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_history',
            name='sales_order',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
