# Generated by Django 2.1.12 on 2019-10-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_auto_20191024_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign_history',
            name='assigned_to',
            field=models.CharField(blank=True, default=None, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='assign_history',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
