# Generated by Django 2.1.12 on 2019-11-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_auto_20191025_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder_new',
            name='sales_order_confirm_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
